<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Patient Cancer Report</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            line-height: 1.6;
            color: #333;
            margin: -80px -50px;
            padding: 0 20px;
        }

        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 20px;
            text-align: center;
            border-radius: 10px;
        }

        .section {
            margin: 0px 0;
            padding: 15px;
            border-radius: 8px;
            background-color: #f7f7f7;
            page-break-inside: avoid;
        }

        .section h2 {
            color: #764ba2;
            margin-bottom: 10px;
        }

        .section p {
            margin: 5px 0;
        }

        .image-container {
            text-align: center;
            margin: 15px 0;
        }

        .image-container img {
            max-width: 300px;
            border-radius: 10px;
            border: 1px solid #ccc;
            display: block;
            margin: 0 auto;
        }

        .confidence-bar-bg {
            width: 100%;
            background-color: #c68d8dff;
            height: 20px;
            border-radius: 10px;
            margin: 5px 0;
        }

        .confidence-bar-fill {
            height: 20px;
            border-radius: 10px;
            background: linear-gradient(135deg, #9605e9ff 0%, #764ba2 100%);
            text-align: right;
            padding-right: 5px;
            color: white;
            font-weight: bold;
            line-height: 20px;
        }

        .footer {
            text-align: center;
            margin-top: 30px;
            font-size: 12px;
            color: #555;
        }
    </style>
</head>

<body>

    <div class="header">
        <h1>Patient Cancer Detection Report</h1>
    </div>

    <!-- Patient Info -->
    <div class="section">
        <h2>Patient Information</h2>
        <p><strong>Name:</strong> {{ $patient->name ?? 'N/A' }}</p>
        <p><strong>Age:</strong> {{ $patient->age ?? 'N/A' }}</p>
        <p><strong>Gender:</strong> {{ $patient->gender ?? 'N/A' }}</p>
        <p><strong>Disease Type:</strong> {{ ucfirst($type ?? 'N/A') }}</p>
    </div>

    <!-- Uploaded Image -->
    <div class="section image-container">
        <h2>Uploaded Image</h2>
        @php
        $imageFullPath = storage_path('app/public/' . $imagePath);
        @endphp
        @if(file_exists($imageFullPath))
        <img src="{{ $imageFullPath }}" alt="Medical Image">
        @else
        <p>Image not found</p>
        @endif
    </div>

    <!-- Prediction Result -->
    <div class="section">
        <h2>AI Prediction</h2>
        <p><strong>Predicted Class:</strong> {{ $result['class'] ?? 'N/A' }}</p>
        <p><strong>Confidence:</strong> {{ number_format($result['confidence'] ?? 0, 2) }}%</p>

        <div class="confidence-bar-bg">
            <div class="confidence-bar-fill" style="width: {{ $result['confidence'] ?? 0 }}%">
                {{ number_format($result['confidence'] ?? 0, 2) }}%
            </div>
        </div>
    </div>

    <!-- Footer -->
    <div class="footer">
        <p>Generated by AI Cancer Detection System | Confidential & HIPAA Compliant</p>
    </div>

</body>

</html>